title: 'EDGE Zine'
description: "Just Another EDGE Zine site."
baseurl: 
url: 

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: light 

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: t3p0s/jekyll-dash
